# Generated by Django 6.0.6 on 2026-06-27 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptops', '0006_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='videobanner',
            name='youtube_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='videobanner',
            name='video_url',
            field=models.URLField(blank=True),
        ),
    ]
