# Generated by Django 6.0.6 on 2026-06-28 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptops', '0010_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='image',
        ),
        migrations.AddField(
            model_name='banner',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
