# Generated by Django 6.0.6 on 2026-06-28 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptops', '0012_alter_laptop_amazon_url_alter_laptop_flipkart_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('reply', models.TextField(blank=True)),
            ],
        ),
    ]
