# Generated by Django 6.0.6 on 2026-07-01 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptops', '0015_review_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='is_replied',
            field=models.BooleanField(default=False),
        ),
    ]
