# Generated by Django 6.0.6 on 2026-07-02 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptops', '0016_contactmessage_is_replied'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=100)),
                ('processor', models.CharField(max_length=200)),
                ('ram', models.CharField(max_length=50)),
                ('ssd', models.CharField(max_length=50)),
                ('display', models.CharField(max_length=100)),
                ('gpu', models.CharField(max_length=100)),
                ('battery', models.CharField(max_length=100)),
                ('portability', models.CharField(max_length=100)),
                ('ports', models.CharField(max_length=200)),
                ('connectivity', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('price_range', models.CharField(max_length=100)),
                ('rating', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
