# Generated by Django 6.0.6 on 2026-07-02 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptops', '0018_remove_comparison_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparison',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
