# Generated by Django 6.0.6 on 2026-07-04 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptops', '0019_comparison_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('mouse', 'Mouse'), ('keyboard', 'Keyboard'), ('headphones', 'Headphones'), ('speaker', 'Speaker'), ('other', 'Other')], max_length=50)),
                ('price', models.IntegerField()),
                ('image_url', models.URLField()),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('amazon_url', models.URLField(blank=True, null=True)),
                ('flipkart_url', models.URLField(blank=True, null=True)),
                ('connectivity', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
