# Generated by Django 6.0.6 on 2026-07-11 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptops', '0022_alter_accessory_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparison',
            name='laptop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='laptops.laptop'),
        ),
    ]
