# Generated by Django 6.0.6 on 2026-06-26 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price_min', models.IntegerField()),
                ('price_max', models.IntegerField()),
                ('rating', models.FloatField(default=4.0)),
                ('image_url', models.URLField()),
                ('amazon_url', models.URLField()),
                ('flipkart_url', models.URLField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laptops.brand')),
            ],
        ),
    ]
