# Generated by Django 6.0.6 on 2026-06-26 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptops', '0002_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon_url', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='laptop',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
