# Generated by Django 6.0.6 on 2026-06-27 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptops', '0003_category_laptop_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='laptops.category'),
        ),
        migrations.AddField(
            model_name='laptop',
            name='is_best_selling',
            field=models.BooleanField(default=False),
        ),
    ]
