# Generated by Django 6.0.6 on 2026-06-27 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptops', '0004_laptop_category_laptop_is_best_selling'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('video_url', models.URLField()),
                ('link', models.URLField(blank=True)),
            ],
        ),
    ]
