# Generated by Django 6.0.6 on 2026-06-27 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptops', '0005_videobanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('image_url', models.URLField()),
                ('price_text', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
