# Generated by Django 6.0.6 on 2026-06-28 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptops', '0007_videobanner_youtube_url_alter_videobanner_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='banner_type',
            field=models.CharField(choices=[('slider', 'Slider'), ('big', 'Big Banner')], default='slider', max_length=20),
            preserve_default=False,
        ),
    ]
