# Generated by Django 6.0.6 on 2026-06-28 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laptops', '0008_banner_banner_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
        migrations.DeleteModel(
            name='Slider',
        ),
        migrations.DeleteModel(
            name='VideoBanner',
        ),
    ]
