# Generated by Django 6.0.6 on 2026-06-28 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptops', '0009_delete_banner_delete_slider_delete_videobanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='banners/')),
                ('banner_type', models.CharField(choices=[('top_slider', 'Top Auto Slider'), ('big_banner', 'Big Banner'), ('carousel', 'Carousel Slider')], max_length=20)),
                ('link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
