# Generated by Django 6.0.6 on 2026-06-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptops', '0011_remove_banner_image_banner_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='amazon_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='flipkart_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
