# Generated by Django 6.0.6 on 2026-06-29 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptops', '0013_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
