# Generated by Django 6.0.6 on 2026-06-29 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptops', '0014_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
