# Generated by Django 6.0.6 on 2026-07-02 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptops', '0017_comparison'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comparison',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='comparison',
            name='price_range',
        ),
        migrations.AddField(
            model_name='comparison',
            name='price',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='comparison',
            name='raw_data',
            field=models.TextField(default='blank', help_text='Paste full specs here'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comparison',
            name='battery',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='comparison',
            name='brand',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='comparison',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='comparison',
            name='connectivity',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='comparison',
            name='display',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='comparison',
            name='gpu',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='comparison',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='comparison',
            name='portability',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='comparison',
            name='ports',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='comparison',
            name='processor',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='comparison',
            name='ram',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='comparison',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comparison',
            name='ssd',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
