# Generated by Django 6.0.6 on 2026-07-04 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptops', '0020_accessory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessory',
            name='amazon_url',
        ),
        migrations.RemoveField(
            model_name='accessory',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='accessory',
            name='connectivity',
        ),
        migrations.RemoveField(
            model_name='accessory',
            name='flipkart_url',
        ),
        migrations.AlterField(
            model_name='accessory',
            name='type',
            field=models.CharField(choices=[('mouse', 'Mouse'), ('keyboard', 'Keyboard'), ('headphones', 'Headphones'), ('speaker', 'Speaker'), ('laptop_bag', 'Laptop Bag'), ('cooling_pad', 'Cooling Pad'), ('webcam', 'Webcam'), ('microphone', 'Microphone'), ('usb_hub', 'USB Hub'), ('adapter', 'Adapter'), ('charger', 'Charger'), ('stand', 'Stand'), ('dock', 'Docking Station'), ('power_bank', 'Power Bank'), ('external_hard_drive', 'External Hard Drive'), ('Stylus Pen', 'Stylus Pen'), ('case', 'Case'), ('screen_protector', 'Screen Protector'), ('Webcam Cover', 'Webcam Cover'), ('other', 'Other')], max_length=50),
        ),
    ]
